[workspace]
name = "cnn_cifar_test"
channels = ["conda-forge", "pytorch", "nvidia"]
platforms = ["linux-64"]
preview = ["pixi-build"]

[dependencies]
python = "3.12.*"
cuda-toolkit = "13.0.*"
cuda-nvcc = "13.0.*"
matplotlib = "3.10.8.*"

[pypi-dependencies]
torch = "==2.11.0"
torchvision = "==0.26.0"
wandb = "==0.26.0"

[system-requirements]
cuda = "13.0"

[tool.pixi.pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cu130"]

[tool.pixi.project]
channel-priority = "flexible"